<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 2</b></center>    
<pre>



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user",sep="|")
df

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. See the first 25 entries

In [5]:
df.head(25)

    user_id  age gender     occupation zip_code
0         1   24      M     technician    85711
1         2   53      F          other    94043
2         3   23      M         writer    32067
3         4   24      M     technician    43537
4         5   33      F          other    15213
5         6   42      M      executive    98101
6         7   57      M  administrator    91344
7         8   36      M  administrator    05201
8         9   29      M        student    01002
9        10   53      M         lawyer    90703
10       11   39      F          other    30329
11       12   28      F          other    06405
12       13   47      M       educator    29206
13       14   45      M      scientist    55106
14       15   49      F       educator    97301
15       16   21      M  entertainment    10309
16       17   30      M     programmer    06355
17       18   35      F          other    37212
18       19   40      M      librarian    02138
19       20   42      F      homemaker    95660
20       21   26      M         writer    30068
21       22   25      M         writer    40206
22       23   30      F         artist    48197
23       24   21      F         artist    94533
24       25   39      M       engineer    55107

### Step 5. See the last 10 entries

In [6]:
df.tail(10)

     user_id  age gender     occupation zip_code
933      934   61      M       engineer    22902
934      935   42      M         doctor    66221
935      936   24      M          other    32789
936      937   48      M       educator    98072
937      938   38      F     technician    55038
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

### Step 6. What is the number of observations in the dataset?

In [8]:
df.shape[0] #is for row

943

### Step 7. What is the number of columns in the dataset?

In [10]:
df.shape[1] #is for columns

5

### Step 8. Print the name of all the columns.

In [11]:
df.columns

Index(['user_id', 'age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

In [12]:
# "the index" (aka "the labels")
df.index

RangeIndex(start=0, stop=943, step=1)

### Step 10. What is the data type of each column?

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 943 entries, 0 to 942
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     943 non-null    int64
 1   age         943 non-null    int64
 2   gender      943 non-null    object
 3   occupation  943 non-null    object
 4   zip_code    943 non-null    object
dtypes: int64(2), object(3)
memory usage: 37.0+ KB

### Step 11. Print only the occupation column

In [16]:
df['occupation']

0         technician
1              other
2             writer
3         technician
4              other
           ...
938          student
939    administrator
940          student
941        librarian
942          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

In [18]:
df['occupation'].unique()

array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 13. What is the most frequent occupation?

In [21]:
df['occupation'].value_counts().head(5)

student          196
other            105
educator          95
administrator     79
engineer          67
Name: occupation, dtype: int64

### Step 14. Summarize the DataFrame.

In [22]:
df.describe()

          user_id         age
count  943.000000  943.000000
mean   472.000000   34.051962
std    272.364951   12.192740
min      1.000000    7.000000
25%    236.500000   25.000000
50%    472.000000   31.000000
75%    707.500000   43.000000
max    943.000000   73.000000

### Step 15. Summarize all the columns

In [23]:
df.describe(include="all")

           user_id         age gender occupation zip_code
count   943.000000  943.000000    943        943      943
unique         NaN         NaN      2         21      795
top            NaN         NaN      M    student    55414
freq           NaN         NaN    670        196        9
mean    472.000000   34.051962    NaN        NaN      NaN
std     272.364951   12.192740    NaN        NaN      NaN
min       1.000000    7.000000    NaN        NaN      NaN
25%     236.500000   25.000000    NaN        NaN      NaN
50%     472.000000   31.000000    NaN        NaN      NaN
75%     707.500000   43.000000    NaN        NaN      NaN
max     943.000000   73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

In [24]:
df["age"].describe()

count    943.000000
mean      34.051962
std       12.192740
min        7.000000
25%       25.000000
50%       31.000000
75%       43.000000
max       73.000000
Name: age, dtype: float64

### Step 17. What is the mean age of users?

In [25]:
df['age'].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

In [31]:
df['age'].value_counts()

30    39
25    38
22    37
28    36
27    35
      ..
7      1
66     1
11     1
10     1
73     1
Name: age, Length: 61, dtype: int64

## Part -2

- **All tasks** are based on the **single dataset** loaded in the Setup cell below.

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 200

cities    = ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix',
             'Philadelphia', 'San Antonio', 'Dallas', 'Austin', 'Seattle']
regions   = {'New York': 'East', 'Los Angeles': 'West', 'Chicago': 'North',
             'Houston': 'South', 'Phoenix': 'West', 'Philadelphia': 'East',
             'San Antonio': 'South', 'Dallas': 'South', 'Austin': 'South', 'Seattle': 'West'}
categories = ['Electronics', 'Clothing', 'Food', 'Furniture']
products   = {
    'Electronics': ['Laptop', 'Smartphone', 'Headphones', 'Tablet', 'Camera'],
    'Clothing':    ['T-Shirt', 'Jeans', 'Jacket', 'Sneakers', 'Dress'],
    'Food':        ['Coffee Beans', 'Olive Oil', 'Pasta', 'Chocolate', 'Tea'],
    'Furniture':   ['Office Chair', 'Desk', 'Bookshelf', 'Sofa', 'Lamp']
}
prices     = {
    'Laptop': 999.99, 'Smartphone': 799.99, 'Headphones': 199.99,
    'Tablet': 499.99, 'Camera': 649.99, 'T-Shirt': 29.99,
    'Jeans': 59.99, 'Jacket': 89.99, 'Sneakers': 79.99, 'Dress': 69.99,
    'Coffee Beans': 14.99, 'Olive Oil': 12.99, 'Pasta': 5.99,
    'Chocolate': 8.99, 'Tea': 9.99, 'Office Chair': 249.99,
    'Desk': 349.99, 'Bookshelf': 149.99, 'Sofa': 799.99, 'Lamp': 49.99
}
salespersons = ['Alice Johnson', 'Bob Martinez', 'Carol White',
                'David Lee', 'Emma Davis']
first_names  = ['James', 'Mary', 'John', 'Patricia', 'Robert', 'Jennifer',
                'Michael', 'Linda', 'William', 'Barbara', 'David', 'Susan',
                'Richard', 'Jessica', 'Thomas', 'Sarah', 'Charles', 'Karen',
                'Daniel', 'Lisa']
last_names   = ['Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia',
                'Miller', 'Davis', 'Wilson', 'Moore', 'Taylor', 'Anderson',
                'Thomas', 'Jackson', 'White', 'Harris', 'Martin', 'Thompson',
                'Young', 'Robinson']

city_list    = np.random.choice(cities, n)
cat_list     = np.random.choice(categories, n)
prod_list    = [np.random.choice(products[c]) for c in cat_list]
price_list   = np.array([prices[p] for p in prod_list])
disc_list    = np.random.choice([0, 5, 10, 15, 20, 25, 30], n)
qty_list     = np.random.randint(1, 11, n)
rating_list  = np.random.choice([1, 2, 3, 4, 5], n, p=[0.05, 0.10, 0.20, 0.40, 0.25])
dates        = pd.date_range(start='2023-01-01', end='2023-12-31', periods=n)
dates        = pd.to_datetime(np.sort(np.random.choice(dates, n, replace=False)))
cust_names   = [f"{np.random.choice(first_names)} {np.random.choice(last_names)}" for _ in range(n)]

# Introduce some missing values
rating_arr = rating_list.astype(float)
rating_arr[np.random.choice(n, 12, replace=False)] = np.nan
disc_arr = disc_list.astype(float)
disc_arr[np.random.choice(n, 8, replace=False)] = np.nan

df = pd.DataFrame({
    'order_id':      [f'ORD-{1000+i}' for i in range(n)],
    'order_date':    dates,
    'customer_name': cust_names,
    'city':          city_list,
    'region':        [regions[c] for c in city_list],
    'category':      cat_list,
    'product':       prod_list,
    'quantity':      qty_list,
    'unit_price':    price_list,
    'discount':      disc_arr,
    'salesperson':   np.random.choice(salespersons, n),
    'rating':        rating_arr
})

# Add duplicate rows intentionally
df = pd.concat([df, df.iloc[[5, 23, 77]]], ignore_index=True)


df.head()

,order_id,order_date,customer_name,city,region,category,product,quantity,unit_price,discount,salesperson,rating
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,NaN
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0

### ✅ Task 1 — First Inspection
Perform a basic inspection of the DataFrame `df`:
1. Display the **first 8 rows**.
2. Display the **last 5 rows**.
3. Print the **shape** (rows, columns).
4. Print all **column names**.

In [10]:
df.head(8)
df.tail(5)
df.shape
df.columns

Index(['order_id', 'order_date', 'customer_name', 'city', 'region', 'category',
       'product', 'quantity', 'unit_price', 'discount', 'salesperson',
       'rating'],
      dtype='object')

### ✅ Task 2 — Data Types & Info
1. Display the **data type** of each column using `.dtypes`.
2. Use `.info()` to get a full summary.
3. Identify which columns have **missing values** and how many.

In [17]:
df.dtypes
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       203 non-null    object
 1   order_date     203 non-null    datetime64[ns]
 2   customer_name  203 non-null    object
 3   city           203 non-null    object
 4   region         203 non-null    object
 5   category       203 non-null    object
 6   product        203 non-null    object
 7   quantity       203 non-null    int64
 8   unit_price     203 non-null    float64
 9   discount       195 non-null    float64
 10  salesperson    203 non-null    object
 11  rating         190 non-null    float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(7)
memory usage: 19.2+ KB

order_id          0
order_date        0
customer_name     0
city              0
region            0
category          0
product           0
quantity          0
unit_price        0
discount          8
salesperson       0
rating           13
dtype: int64

### ✅ Task 3 — Descriptive Statistics
1. Use `.describe()` to get summary statistics for **all numeric columns**.
2. Use `.describe(include='object')` to get statistics for **text columns**.
3. Print the **mean**, **min**, and **max** of `unit_price` separately.

In [22]:
df.describe()
df.describe(include='object')
df['unit_price'].mean()
df['unit_price'].min()
df['unit_price'].max()

999.99

### ✅ Task 4 — Selecting Columns
1. Select and display only the `customer_name` and `city` columns.
2. Select the columns `product`, `quantity`, `unit_price` and display the **first 10 rows**.
3. Store the `unit_price` column as a **Pandas Series** named `prices_series` and print its type.

In [25]:
df[['customer_name','city']]
df[['product','quantity','unit_price']].head(10)
prices_series = df['unit_price']
print(type(prices_series))

<class 'pandas.core.series.Series'>

### ✅ Task 5 — Filtering Rows
Filter and display:
1. All orders from the **'Electronics'** category.
2. All orders where `quantity` is **greater than 7**.
3. All orders from **'New York'** city.
4. Print the **row count** for each filtered result.

In [28]:
ele = df[df['category'] == 'Electronics']
qua= df[df['quantity'] > 7]
new = df[df['city'] == 'New York']

print("electronics orders row count:", elec.shape[0])
print("quantity > 7 row count:", qua.shape[0])
print("new york orders row count:", ne.shape[0])

Electronics Orders Row Count: 48
Quantity > 7 Row Count: 57
New York Orders Row Count: 23

### ✅ Task 6 — Sorting
1. Sort the DataFrame by `unit_price` in **descending order** and display the top 10 rows.
2. Sort by `category` (ascending) and then by `unit_price` (descending) — **multi-column sort**.
3. Display the **cheapest 5 products** (by unit_price).

In [30]:
# 1
sorted_pri = df.sort_values(by='unit_price', ascending=False)
print(sorted_pri.head(10))

# 2
sorte = df.sort_values(by=['category', 'unit_price'],ascending=[True, False])
print(sorte)

#3
cheap = df.sort_values(by='unit_price', ascending=True)
print(cheap.head(5))

     order_id                    order_date    customer_name         city  \
167  ORD-1167 2023-11-02 11:12:57.889447236      Karen White      Houston
200  ORD-1005 2023-01-10 03:29:50.954773869     Susan Thomas      Seattle
63   ORD-1063 2023-04-26 05:40:06.030150754    David Johnson      Seattle
33   ORD-1033 2023-03-02 08:41:00.301507538      Susan Jones      Chicago
74   ORD-1074 2023-05-16 08:33:46.130653266     Linda Thomas       Dallas
176  ORD-1176 2023-11-18 22:18:41.608040200   Linda Thompson     New York
129  ORD-1129 2023-08-24 23:02:06.633165828    Mary Williams  San Antonio
180  ORD-1180 2023-11-26 05:54:34.371859296  Patricia Garcia  San Antonio
6    ORD-1006 2023-01-11 23:23:49.145728643    Mary Williams      Chicago
5    ORD-1005 2023-01-10 03:29:50.954773869     Susan Thomas      Seattle

    region     category product  quantity  unit_price  discount  \
167  South  Electronics  Laptop         9      999.99       5.0
200   West  Electronics  Laptop         5      999.99      20.0
63    West  Electronics  Laptop         1      999.99      10.0
33   North  Electronics  Laptop         6      999.99      20.0
74   South  Electronics  Laptop         2      999.99      10.0
176   East  Electronics  Laptop         9      999.99      10.0
129  South  Electronics  Laptop        10      999.99      10.0
180  South  Electronics  Laptop         5      999.99       0.0
6    North  Electronics  Laptop         5      999.99      15.0
5     West  Electronics  Laptop         5      999.99      20.0

       salesperson  rating
167     Emma Davis     3.0
200     Emma Davis     4.0
63     Carol White     4.0
33   Alice Johnson     5.0
74    Bob Martinez     NaN
176      David Lee     4.0
129      David Lee     3.0
180   Bob Martinez     4.0
6       Emma Davis     NaN
5       Emma Davis     4.0
     order_id                    order_date    customer_name          city  \
0    ORD-1000 2023-01-01 00:00:00.000000000   Karen Robinson   San Antonio
56   ORD-1056 2023-04-13 10:22:18.693467337   Robert Johnson   Los Angeles
81   ORD-1081 2023-05-29 03:51:33.467336684    Barbara Brown        Austin
124  ORD-1124 2023-08-15 19:32:15.678391960      Sarah Jones      New York
127  ORD-1127 2023-08-21 07:14:10.251256284       John Smith       Phoenix
..        ...                           ...              ...           ...
109  ORD-1109 2023-07-19 09:02:42.814070352     Susan Miller       Chicago
152  ORD-1152 2023-10-06 00:43:25.025125628  Jennifer Wilson  Philadelphia
154  ORD-1154 2023-10-09 16:31:21.407035176    Daniel Wilson        Austin
172  ORD-1172 2023-11-11 14:42:48.844221108   William Garcia       Phoenix
183  ORD-1183 2023-12-01 17:36:28.944723620   David Thompson      New York

    region   category product  quantity  unit_price  discount    salesperson  \
0    South   Clothing  Jacket         1       89.99      10.0      David Lee
56    West   Clothing  Jacket         9       89.99       0.0      David Lee
81   South   Clothing  Jacket         7       89.99      15.0      David Lee
124   East   Clothing  Jacket         6       89.99      30.0    Carol White
127   West   Clothing  Jacket         8       89.99      25.0      David Lee
..     ...        ...     ...       ...         ...       ...            ...
109  North  Furniture    Lamp         9       49.99      20.0      David Lee
152   East  Furniture    Lamp         4       49.99      25.0    Carol White
154  South  Furniture    Lamp         4       49.99       0.0     Emma Davis
172   West  Furniture    Lamp         2       49.99       5.0  Alice Johnson
183   East  Furniture    Lamp         7       49.99       5.0   Bob Martinez

     rating
0       5.0
56      4.0
81      4.0
124     2.0
127     5.0
..      ...
109     4.0
152     3.0
154     3.0
172     5.0
183     4.0

[203 rows x 12 columns]

### ✅ Task 7 — Value Counts
1. Count how many orders belong to each **category**.
2. Count how many orders were handled by each **salesperson**.
3. Find the **most common city** in the dataset.
4. Show the distribution of **customer ratings** (including NaN count).

In [34]:
#1
df['category'].value_counts()
#2
df['salesperson'].value_counts()
#3
df['city'].value_counts().idxmax()
#4
df['rating'].value_counts(dropna=False)

rating
4.0    85
5.0    49
3.0    33
2.0    17
NaN    13
1.0     6
Name: count, dtype: int64

### ✅ Task 8 — Adding a New Column
Add a new column called **`total_revenue`** computed as:
> `total_revenue = quantity × unit_price × (1 - discount / 100)`

> ⚠️ Treat missing `discount` values as **0** (no discount).

Print the first 10 rows showing `product`, `quantity`, `unit_price`, `discount`, and `total_revenue`.

In [35]:
df['total_revenue'] = (df['quantity'] * df['unit_price'] * (1 - df['discount'].fillna(0) / 100))

print(df[['product', 'quantity', 'unit_price', 'discount', 'total_revenue']].head(10))

        product  quantity  unit_price  discount  total_revenue
0        Jacket         1       89.99      10.0        80.9910
1     Olive Oil         5       12.99      15.0        55.2075
2     Olive Oil         7       12.99       0.0        90.9300
3          Desk         6      349.99      15.0      1784.9490
4  Office Chair         1      249.99      10.0       224.9910
5        Laptop         5      999.99      20.0      3999.9600
6        Laptop         5      999.99      15.0      4249.9575
7     Bookshelf         6      149.99      20.0       719.9520
8           Tea         3        9.99      30.0        20.9790
9         Jeans         5       59.99       0.0       299.9500

### ✅ Task 9 — Handling Missing Values
1. Count the total number of missing values in the **entire DataFrame**.
2. Fill missing `rating` values with the **median** rating.
3. Fill missing `discount` values with **0**.
4. Confirm there are **no more missing values** after filling.

In [41]:
#1
df.isnull().sum().sum()
#2
med = df['rating'].median()
df['rating'] = df['rating'].fillna(med)
#3
df['discount'] = df['discount'].fillna(0)
#4
df.isnull().sum().sum()

np.int64(0)

### ✅ Task 10 — Removing Duplicates
1. Check how many **duplicate rows** exist in the DataFrame.
2. Display the duplicate rows.
3. Remove duplicates and store the clean DataFrame back into `df`.
4. Confirm the new shape.

In [47]:
#1
df.duplicated().sum()
#2
df[df.duplicated()]
#3
df.drop_duplicates()
#4
print("New Shape:", df.shape)

New Shape: (203, 13)

### ✅ Task 11 — Renaming and Dropping Columns
1. Rename the column `unit_price` to `price_usd` and `customer_name` to `customer`.
2. Drop the column `order_id` from a **copy** of the DataFrame (do not modify `df`).
3. Reset the index of that copy and print it.

In [54]:
#1
df = df.rename(columns={
    'unit_price': 'price_usd',
    'customer_name': 'customer'
})
#2
df_copy = df.drop('order_id', axis=1)
#3
df_copy = df_copy.reset_index(drop=True)
#4
df_copy

,order_date,customer,city,region,category,product,quantity,price_usd,discount,salesperson,rating,total_revenue
0,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,10.0,David Lee,5.0,80.9910
1,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0,55.2075
2,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,4.0,90.9300
3,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0,1784.9490
4,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0,224.9910
...,...,...,...,...,...,...,...,...,...,...,...,...
198,2023-12-29 04:06:01.809045228,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0,39.9600
199,2023-12-31 00:00:00.000000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,4.0,377.9460
200,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,3999.9600
201,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,4.0,134.9910
202,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0,18.9810

### ✅ Task 12 — `loc` and `iloc`
Using the original `df`:
1. Use **`iloc`** to select rows 10 to 20 and the first 4 columns.
2. Use **`loc`** to select all rows where `region == 'West'`, showing only `city`, `product`, and `unit_price`.
3. Use **`loc`** to update the `discount` of row at index `0` to `50`.

In [61]:
df.iloc[10:21, 0:4]

    order_id                    order_date          customer          city
10  ORD-1010 2023-01-19 06:59:41.909547738     Charles Brown       Houston
11  ORD-1011 2023-01-21 02:53:40.100502512  Richard Thompson        Dallas
12  ORD-1012 2023-01-22 22:47:38.291457286      James Harris        Dallas
13  ORD-1013 2023-01-24 18:41:36.482412060     Richard Moore       Chicago
14  ORD-1014 2023-01-26 14:35:34.673366834     Susan Johnson  Philadelphia
15  ORD-1015 2023-01-28 10:29:32.864321608        John Moore       Phoenix
16  ORD-1016 2023-01-30 06:23:31.055276382       Mary Thomas   Los Angeles
17  ORD-1017 2023-02-01 02:17:29.246231156  Richard Thompson        Dallas
18  ORD-1018 2023-02-02 22:11:27.437185930       John Miller  Philadelphia
19  ORD-1019 2023-02-04 18:05:25.628140703  Jessica Robinson   Los Angeles
20  ORD-1020 2023-02-06 13:59:23.819095477  Charles Anderson       Phoenix

In [60]:
df.loc[df['region'] == 'West',['city', 'product', 'price_usd']]

            city       product  price_usd
3        Phoenix          Desk     349.99
5        Seattle        Laptop     999.99
9        Phoenix         Jeans      59.99
15       Phoenix     Chocolate       8.99
16   Los Angeles          Desk     349.99
19   Los Angeles           Tea       9.99
20       Phoenix     Chocolate       8.99
22       Seattle          Sofa     799.99
26       Seattle    Smartphone     799.99
32       Phoenix          Desk     349.99
35       Phoenix          Desk     349.99
38   Los Angeles         Dress      69.99
41   Los Angeles      Sneakers      79.99
42       Seattle      Sneakers      79.99
44       Seattle           Tea       9.99
45       Phoenix          Sofa     799.99
46   Los Angeles          Lamp      49.99
53   Los Angeles         Jeans      59.99
56   Los Angeles        Jacket      89.99
59       Seattle    Smartphone     799.99
62   Los Angeles           Tea       9.99
63       Seattle        Laptop     999.99
64   Los Angeles        Tablet     499.99
65       Seattle           Tea       9.99
71       Phoenix  Office Chair     249.99
72   Los Angeles         Dress      69.99
73       Phoenix          Lamp      49.99
75       Seattle          Lamp      49.99
92       Phoenix         Jeans      59.99
93       Seattle          Lamp      49.99
95       Seattle       T-Shirt      29.99
100  Los Angeles        Tablet     499.99
105      Phoenix    Headphones     199.99
112      Phoenix  Office Chair     249.99
115      Phoenix        Tablet     499.99
116      Seattle          Sofa     799.99
120      Seattle  Coffee Beans      14.99
121      Seattle  Coffee Beans      14.99
127      Phoenix        Jacket      89.99
134  Los Angeles           Tea       9.99
135      Seattle      Sneakers      79.99
137      Phoenix         Dress      69.99
140      Seattle         Pasta       5.99
155      Phoenix     Bookshelf     149.99
158      Seattle       T-Shirt      29.99
166      Seattle    Headphones     199.99
169  Los Angeles        Tablet     499.99
172      Phoenix          Lamp      49.99
177  Los Angeles    Headphones     199.99
178  Los Angeles  Office Chair     249.99
181      Phoenix          Sofa     799.99
185  Los Angeles    Headphones     199.99
186      Phoenix       T-Shirt      29.99
187      Seattle     Chocolate       8.99
196      Phoenix         Pasta       5.99
198  Los Angeles           Tea       9.99
200      Seattle        Laptop     999.99

In [62]:
df.loc[0, 'discount'] = 50

In [63]:
df

,order_id,order_date,customer,city,region,category,product,quantity,price_usd,discount,salesperson,rating,total_revenue
0,ORD-1000,2023-01-01 00:00:00.000000000,Karen Robinson,San Antonio,South,Clothing,Jacket,1,89.99,50.0,David Lee,5.0,80.9910
1,ORD-1001,2023-01-02 19:53:58.190954773,Michael Williams,Houston,South,Food,Olive Oil,5,12.99,15.0,David Lee,4.0,55.2075
2,ORD-1002,2023-01-04 15:47:56.381909547,Karen Moore,Dallas,South,Food,Olive Oil,7,12.99,0.0,Bob Martinez,4.0,90.9300
3,ORD-1003,2023-01-06 11:41:54.572864321,Michael Martin,Phoenix,West,Furniture,Desk,6,349.99,15.0,David Lee,5.0,1784.9490
4,ORD-1004,2023-01-08 07:35:52.763819095,Jessica Williams,San Antonio,South,Furniture,Office Chair,1,249.99,10.0,Emma Davis,4.0,224.9910
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,ORD-1198,2023-12-29 04:06:01.809045228,Robert Brown,Los Angeles,West,Food,Tea,4,9.99,0.0,Alice Johnson,4.0,39.9600
199,ORD-1199,2023-12-31 00:00:00.000000000,Susan Robinson,Philadelphia,East,Clothing,Dress,6,69.99,10.0,Bob Martinez,4.0,377.9460
200,ORD-1005,2023-01-10 03:29:50.954773869,Susan Thomas,Seattle,West,Electronics,Laptop,5,999.99,20.0,Emma Davis,4.0,3999.9600
201,ORD-1023,2023-02-12 01:41:18.391959799,Michael Robinson,Philadelphia,East,Furniture,Bookshelf,1,149.99,10.0,Emma Davis,4.0,134.9910
202,ORD-1077,2023-05-21 20:15:40.703517588,Sarah Davis,Austin,South,Food,Tea,2,9.99,5.0,Bob Martinez,4.0,18.9810

In [ ]:
# loc = row labels + column names
# iloc = row positions + column positions