# Dataset - `50_Startups.csv`

# 1. Import Libraries: Import the necessary libraries.

In [1]:
import pandas as pd

# 2. Import Dataset: Import the dataset `50_Startups.csv`

In [2]:
df = pd.read_csv('50_Startups.csv')

In [4]:
df.head()

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

# 3. Exploratory Data Analysis: 
## Check the `State` column to understand its unique values.

In [5]:
df['State'].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

# 4. Feature Selection: Split the dataset into input (independent variables) 
## and output (dependent variable/Profit).

In [7]:
X = df[['R&D Spend','Administration','Marketing Spend']]

In [11]:
y = df['Profit']

# 5. Data Preprocessing (Encoding): 
## Convert the 'State' column into a numeric column using transformation.

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
le = LabelEncoder()
df['State'] = le.fit_transform(df['State'])

In [39]:
df.head()

   R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

# 6. Dummy Variable Trap: 
## Handle the dummy variable trap (if manual encoding was used).

**Not require to do**

# 7. Train-Test Split: Split the dataset into Training and Testing sets.

In [18]:
X = df.drop('Profit',axis =1 )
y=df['Profit']

In [19]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

# 8. Model Initialization: 
## Import the `LinearRegression` model from the `linear_model` family.

In [26]:
from sklearn.linear_model import LinearRegression

# 9. Model Training: 
## Fit the `Linear Regression` model to the training data.

In [27]:
model = LinearRegression()

In [29]:
model.fit(X_train,y_train)

LinearRegression()

# 10. Prediction & Evaluation: 
## (Implied next steps) Predict results and compare them with actual values.

In [31]:
y_pred =  model.predict(X_test)

In [33]:
from sklearn.metrics import r2_score

In [35]:
r2 = r2_score(y_test,y_pred) *100
r2

90.00614254946403